# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testRN
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'testRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testRN-tvOS

  target 'testRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
